export const obj = [{
    "id": 818771926,
    "node_id": "R_kgDOMM131g",
    "name": "AluraBooks",
    "full_name": "FabricioOliveira1/AluraBooks",
    "private": false,
    "owner": {
      "login": "FabricioOliveira1",
      "id": 83975625,
      "node_id": "MDQ6VXNlcjgzOTc1NjI1",
      "avatar_url": "https://avatars.githubusercontent.com/u/83975625?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/FabricioOliveira1",
      "html_url": "https://github.com/FabricioOliveira1",
      "followers_url": "https://api.github.com/users/FabricioOliveira1/followers",
      "following_url": "https://api.github.com/users/FabricioOliveira1/following{/other_user}",
      "gists_url": "https://api.github.com/users/FabricioOliveira1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/FabricioOliveira1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/FabricioOliveira1/subscriptions",
      "organizations_url": "https://api.github.com/users/FabricioOliveira1/orgs",
      "repos_url": "https://api.github.com/users/FabricioOliveira1/repos",
      "events_url": "https://api.github.com/users/FabricioOliveira1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/FabricioOliveira1/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/FabricioOliveira1/AluraBooks",
    "description": 'React',
    "fork": false,
    "url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks",
    "forks_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/forks",
    "keys_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/teams",
    "hooks_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/hooks",
    "issue_events_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/issues/events{/number}",
    "events_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/events",
    "assignees_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/assignees{/user}",
    "branches_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/branches{/branch}",
    "tags_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/tags",
    "blobs_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/languages",
    "stargazers_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/stargazers",
    "contributors_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/contributors",
    "subscribers_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/subscribers",
    "subscription_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/subscription",
    "commits_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/contents/{+path}",
    "compare_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/merges",
    "archive_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/downloads",
    "issues_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/issues{/number}",
    "pulls_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/labels{/name}",
    "releases_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/releases{/id}",
    "deployments_url": "https://api.github.com/repos/FabricioOliveira1/AluraBooks/deployments",
    "created_at": "2024-06-22T20:22:27Z",
    "updated_at": "2024-07-02T02:30:31Z",
    "pushed_at": "2024-07-02T02:30:28Z",
    "git_url": "git://github.com/FabricioOliveira1/AluraBooks.git",
    "ssh_url": "git@github.com:FabricioOliveira1/AluraBooks.git",
    "clone_url": "https://github.com/FabricioOliveira1/AluraBooks.git",
    "svn_url": "https://github.com/FabricioOliveira1/AluraBooks",
    "homepage": "https://alura-books-xi-one.vercel.app",
    "size": 1808,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
]

  export const objetoDasLinguagens = {
    
        "HTML": 13647,
        "CSS": 10175
      
  }
